### ISSUE TITLE
Delete Superficial Files

### ISSUE THREAD

**Issue by icemarkom** [zwiftcrushindaddies/zwiftcrushindaddies.github.io#1]
Initial commits seem to contain files that are the result of the test build, and not something we should keep in the repo.

Specifically, `.hugo_build.lock` and `.gitmodules` caught my attention. I am not sure about the second one, but lock file surely doesn't belong.

**Comment by icemarkom** [comment]
Looks like we have a bunch of `.DS_Store`s lying around, as well.

**Comment by pdavlin** [comment]
deleted
